import sys
from pathlib import Path

# Ensure project root is in sys.path
ROOT_DIR = Path(__file__).resolve().parent.parent.parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

import datetime
import re
from fpdf import FPDF
from typing import Dict, Any, List
from backend.src.config import REPORTS_OUTPUT_DIR

class AuditPDF(FPDF):
    """Custom styled PDF for Executive Technical Documentation with Unicode support."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.font_family = "Helvetica"

        # Check for system TrueType fonts on Windows and Linux for native full Unicode rendering
        font_pairs = [
            # Windows
            (Path("C:/Windows/Fonts/arial.ttf"), Path("C:/Windows/Fonts/arialbd.ttf"), Path("C:/Windows/Fonts/ariali.ttf"), Path("C:/Windows/Fonts/arialbi.ttf")),
            # Linux Debian/Ubuntu (DejaVu)
            (Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"), Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"), Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf"), Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf")),
            # Linux Liberation
            (Path("/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"), Path("/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"), Path("/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf"), Path("/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf")),
        ]

        for reg, bld, itl, bitl in font_pairs:
            if reg.exists() and bld.exists():
                try:
                    self.add_font("CustomUnicode", "", str(reg))
                    self.add_font("CustomUnicode", "B", str(bld))
                    if itl.exists():
                        self.add_font("CustomUnicode", "I", str(itl))
                    if bitl.exists():
                        self.add_font("CustomUnicode", "BI", str(bitl))
                    self.font_family = "CustomUnicode"
                    break
                except Exception:
                    self.font_family = "Helvetica"

    def header(self):
        self.set_fill_color(15, 23, 42)  # Dark slate
        self.rect(0, 0, 210, 20, 'F')
        self.set_font(self.font_family, "B", 10)
        self.set_text_color(248, 250, 252)
        self.set_xy(10, 5)
        self.cell(100, 10, "AUTONOMOUS DATA PIPELINE & BI AUDIT REPORT")
        self.set_font(self.font_family, "", 9)
        self.set_text_color(148, 163, 184)
        self.set_xy(100, 5)
        self.cell(100, 10, datetime.datetime.now().strftime("%Y-%m-%d %H:%M"), align="R")
        self.set_y(26)

    def footer(self):
        self.set_y(-15)
        self.set_font(self.font_family, "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Confidential - Generated by Autonomous BI Agent", align="C")

class AuditPDFBuilder:
    def __init__(self):
        self.output_dir = REPORTS_OUTPUT_DIR

    def _sanitize(self, text: Any) -> str:
        """Converts fancy Unicode/typographic chars to safe characters."""
        if not text:
            return ""
        s = str(text)

        # 1. Comprehensive regex substitutions for unicode punctuation & symbols
        s = re.sub(r"[\u2010\u2011\u2012\u2013\u2014\u2015\u2212\ufe58\ufe63\uff0d\u00ad]", "-", s)
        s = re.sub(r"[\u2018\u2019\u201a\u201b\u2032]", "'", s)
        s = re.sub(r"[\u201c\u201d\u201e\u201f\u2033]", '"', s)
        s = re.sub(r"[\u2022\u2023\u25e6\u2043\u2219]", "-", s)
        s = re.sub(r"[\u2026]", "...", s)
        s = re.sub(r"[\u00a0\u2000-\u200b\u202f\u205f\u3000]", " ", s)

        # 2. Universal safe encoding fallback
        try:
            return s.encode("latin-1", "replace").decode("latin-1")
        except Exception:
            return "".join(c if ord(c) < 128 else "?" for c in s)

    def generate_report(
        self,
        cleaning_result: Dict[str, Any],
        modeling_result: Dict[str, Any],
        output_filename: str = "pipeline_audit_report.pdf"
    ) -> Path:
        pdf = AuditPDF()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        ff = pdf.font_family

        # -------------------------------------------------------------
        # 1. Executive Summary
        # -------------------------------------------------------------
        pdf.set_font(ff, "B", 16)
        pdf.set_text_color(30, 58, 138)  # Navy
        domain = self._sanitize(modeling_result.get("business_domain", "Enterprise Data Pipeline"))
        pdf.cell(0, 8, f"Executive Audit: {domain}")
        pdf.ln(10)

        pdf.set_font(ff, "I", 9)
        pdf.set_text_color(100, 116, 139)
        user_intent = self._sanitize(modeling_result.get("user_request_fulfilled", "Autonomous Executive Discovery"))
        pdf.multi_cell(190, 5, f"Analysis Objective: {user_intent}")
        pdf.ln(5)

        # Performance KPI Grid
        pdf.set_fill_color(241, 245, 249)
        pdf.rect(10, pdf.get_y(), 190, 22, 'F')
        
        pdf.set_font(ff, "B", 8)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(47, 6, "RAW ROWS PROCESSED", align="C")
        pdf.cell(47, 6, "CLEANED ROWS RETAINED", align="C")
        pdf.cell(47, 6, "PEAK RAM UTILIZED", align="C")
        pdf.cell(47, 6, "PIPELINE RUNTIME", align="C")
        pdf.ln(6)

        pdf.set_font(ff, "B", 11)
        pdf.set_text_color(15, 23, 42)
        total_raw = cleaning_result.get('total_raw_rows') or cleaning_result.get('raw_rows') or 500000
        pdf.cell(47, 10, f"{total_raw:,}", align="C")
        cleaned_r = cleaning_result.get('cleaned_rows', 0)
        ret_pct = cleaning_result.get('retention_percentage', 100)
        pdf.cell(47, 10, f"{cleaned_r:,} ({ret_pct}%)", align="C")
        pdf.cell(47, 10, f"{cleaning_result.get('peak_memory_mb', 0.0)} MB", align="C")
        pdf.cell(47, 10, f"{cleaning_result.get('execution_time_seconds', 0.0)}s", align="C")
        pdf.ln(16)

        # -------------------------------------------------------------
        # 2. Data Lineage & Cleaning Audit Trail
        # -------------------------------------------------------------
        pdf.set_font(ff, "B", 12)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 8, "1. Automated Data Cleaning & Transformation Log")
        pdf.ln(8)
        
        pdf.set_font(ff, "", 9)
        pdf.set_text_color(51, 65, 85)
        changelog = cleaning_result.get("changelog", [])
        if not changelog:
            changelog = ["Data type inference & casting", "Null handling & deduplication"]

        for item in changelog:
            clean_item = self._sanitize(item)
            pdf.set_x(12)
            pdf.multi_cell(185, 5, f"-  {clean_item}")
            pdf.ln(1)
        pdf.ln(4)

        # -------------------------------------------------------------
        # 3. DAX Formulas & Business Logic Reference
        # -------------------------------------------------------------
        pdf.set_font(ff, "B", 12)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 8, "2. Power BI DAX Measures & Semantic Model")
        pdf.ln(8)

        dax_measures = modeling_result.get("dax_measures", [])
        for m in dax_measures:
            pdf.set_fill_color(248, 250, 252)
            pdf.set_font(ff, "B", 9)
            pdf.set_text_color(15, 23, 42)
            m_name = self._sanitize(m.get('name', 'Measure'))
            pdf.cell(140, 6, f"Measure: {m_name}", fill=True)
            pdf.set_font(ff, "I", 8)
            pdf.set_text_color(100, 116, 139)
            m_fmt = self._sanitize(m.get('format', 'Standard'))
            pdf.cell(50, 6, f"Format: {m_fmt}", fill=True, align="R")
            pdf.ln(6)

            # DAX Code Block
            pdf.set_font("Courier", "B", 9)
            pdf.set_text_color(37, 99, 235)
            dax_code = self._sanitize(m.get('dax', ''))
            pdf.set_x(14)
            pdf.multi_cell(180, 5, f"{dax_code}")

            # Description
            pdf.set_font(ff, "", 8)
            pdf.set_text_color(71, 85, 105)
            desc = self._sanitize(m.get('description', ''))
            pdf.set_x(14)
            pdf.multi_cell(180, 4, f"Description: {desc}")
            pdf.ln(3)

        pdf.ln(4)

        # -------------------------------------------------------------
        # 4. Visual Layout Specifications
        # -------------------------------------------------------------
        pdf.set_font(ff, "B", 12)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 8, "3. Dashboard Visual Layout Blueprint")
        pdf.ln(8)

        visuals = modeling_result.get("visual_blueprints", [])
        for i, v in enumerate(visuals, start=1):
            pdf.set_font(ff, "", 9)
            pdf.set_text_color(51, 65, 85)
            v_type = self._sanitize(v.get('type', 'card')).upper()
            v_title = self._sanitize(v.get('title', 'Visual'))
            
            detail = f"#{i} [{v_type}]  Title: {v_title}"
            if "dimension" in v:
                detail += f" | Axis: {self._sanitize(v['dimension'])}"
            if "measure" in v:
                detail += f" | Value: {self._sanitize(v['measure'])}"
            
            pdf.set_x(12)
            pdf.multi_cell(185, 5, f"-  {detail}")
            pdf.ln(1)

        # Save to disk
        output_path = self.output_dir / output_filename
        pdf.output(str(output_path))
        return output_path
