[theme]
base = "light"
primaryColor = "#F59E0B"
backgroundColor = "#F3F5EA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false